server.port=8080

spring.application.name=DoAnJava

spring.mongodb.uri=mongodb+srv://QuocQuan:hongquan12@mongodb.uh7mya4.mongodb.net/tea_and_cake_db?retryWrites=true&w=majority&appName=MongoDB


app.admin.username=admin
app.admin.password=admin123